//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 01:38:41 AM PST 
//


package com.microsoft.hsg.thing.oxm.jaxb.asthmainhaler;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.microsoft.hsg.thing.oxm.jaxb.base.CodableValue;
import com.microsoft.hsg.thing.oxm.jaxb.dates.ApproxDateTime;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:inhaler="urn:com.microsoft.wc.thing.inhaler" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;
 *                         Any inhaler unit used to treat asthma.
 *                     &lt;/summary&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:inhaler="urn:com.microsoft.wc.thing.inhaler" xmlns:t="urn:com.microsoft.wc.thing.types"&gt;
 *                         The inhaler may or may not have a device component.
 *                         Each new canister should have a new inhaler thing, even
 *                         if there is a containing device that is reusable. 
 *                         Changes in regimen (min/max doses per day) should also
 *                         cause a new thing to be created.
 *                     &lt;/remarks&gt;
 * </pre>
 * 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="drug" type="{urn:com.microsoft.wc.thing.types}codable-value"/>
 *         &lt;element name="strength" type="{urn:com.microsoft.wc.thing.types}codable-value" minOccurs="0"/>
 *         &lt;element name="purpose" type="{urn:com.microsoft.wc.thing.inhaler}purpose" minOccurs="0"/>
 *         &lt;element name="start-date" type="{urn:com.microsoft.wc.dates}approx-date-time"/>
 *         &lt;element name="stop-date" type="{urn:com.microsoft.wc.dates}approx-date-time" minOccurs="0"/>
 *         &lt;element name="expiration-date" type="{urn:com.microsoft.wc.dates}approx-date-time" minOccurs="0"/>
 *         &lt;element name="device-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="initial-doses" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="min-daily-doses" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="max-daily-doses" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="can-alert" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="alert" type="{urn:com.microsoft.wc.thing.inhaler}alert" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drug",
    "strength",
    "purpose",
    "startDate",
    "stopDate",
    "expirationDate",
    "deviceId",
    "initialDoses",
    "minDailyDoses",
    "maxDailyDoses",
    "canAlert",
    "alert"
})
@XmlRootElement(name = "asthma-inhaler")
public class AsthmaInhaler {

    @XmlElement(required = true)
    protected CodableValue drug;
    protected CodableValue strength;
    protected Purpose purpose;
    @XmlElement(name = "start-date", required = true)
    protected ApproxDateTime startDate;
    @XmlElement(name = "stop-date")
    protected ApproxDateTime stopDate;
    @XmlElement(name = "expiration-date")
    protected ApproxDateTime expirationDate;
    @XmlElement(name = "device-id")
    protected String deviceId;
    @XmlElement(name = "initial-doses")
    protected Integer initialDoses;
    @XmlElement(name = "min-daily-doses")
    protected Integer minDailyDoses;
    @XmlElement(name = "max-daily-doses")
    protected Integer maxDailyDoses;
    @XmlElement(name = "can-alert")
    protected Boolean canAlert;
    protected List<Alert> alert;

    /**
     * Gets the value of the drug property.
     * 
     * @return
     *     possible object is
     *     {@link CodableValue }
     *     
     */
    public CodableValue getDrug() {
        return drug;
    }

    /**
     * Sets the value of the drug property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodableValue }
     *     
     */
    public void setDrug(CodableValue value) {
        this.drug = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link CodableValue }
     *     
     */
    public CodableValue getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodableValue }
     *     
     */
    public void setStrength(CodableValue value) {
        this.strength = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link Purpose }
     *     
     */
    public Purpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purpose }
     *     
     */
    public void setPurpose(Purpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link ApproxDateTime }
     *     
     */
    public ApproxDateTime getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApproxDateTime }
     *     
     */
    public void setStartDate(ApproxDateTime value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the stopDate property.
     * 
     * @return
     *     possible object is
     *     {@link ApproxDateTime }
     *     
     */
    public ApproxDateTime getStopDate() {
        return stopDate;
    }

    /**
     * Sets the value of the stopDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApproxDateTime }
     *     
     */
    public void setStopDate(ApproxDateTime value) {
        this.stopDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link ApproxDateTime }
     *     
     */
    public ApproxDateTime getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApproxDateTime }
     *     
     */
    public void setExpirationDate(ApproxDateTime value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the deviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * Sets the value of the deviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceId(String value) {
        this.deviceId = value;
    }

    /**
     * Gets the value of the initialDoses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialDoses() {
        return initialDoses;
    }

    /**
     * Sets the value of the initialDoses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialDoses(Integer value) {
        this.initialDoses = value;
    }

    /**
     * Gets the value of the minDailyDoses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinDailyDoses() {
        return minDailyDoses;
    }

    /**
     * Sets the value of the minDailyDoses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinDailyDoses(Integer value) {
        this.minDailyDoses = value;
    }

    /**
     * Gets the value of the maxDailyDoses property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxDailyDoses() {
        return maxDailyDoses;
    }

    /**
     * Sets the value of the maxDailyDoses property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxDailyDoses(Integer value) {
        this.maxDailyDoses = value;
    }

    /**
     * Gets the value of the canAlert property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanAlert() {
        return canAlert;
    }

    /**
     * Sets the value of the canAlert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanAlert(Boolean value) {
        this.canAlert = value;
    }

    /**
     * Gets the value of the alert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Alert }
     * 
     * 
     */
    public List<Alert> getAlert() {
        if (alert == null) {
            alert = new ArrayList<Alert>();
        }
        return this.alert;
    }

}
