//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:25:08 AM PDT 
//


package com.microsoft.healthvault.methods.AuthorizeRecord.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.AuthorizeRecord" xmlns:wc-app="urn:com.microsoft.wc.application" xmlns:wc-auth="urn:com.microsoft.wc.auth" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.AuthorizeRecord" xmlns:wc-app="urn:com.microsoft.wc.application" xmlns:wc-auth="urn:com.microsoft.wc.auth" xmlns:wc-types="urn:com.microsoft.wc.types"/&gt;
 * </pre>
 * 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="user-initiated-creation-using-email" type="{urn:com.microsoft.wc.methods.AuthorizeRecord}UserInitiatedCreationUsingEmail"/>
 *           &lt;element name="resend-authorization-email" type="{urn:com.microsoft.wc.methods.AuthorizeRecord}ResendAuthorizationEmail"/>
 *           &lt;element name="app-behest-creation2" type="{urn:com.microsoft.wc.methods.AuthorizeRecord}AppBehestCreation2"/>
 *           &lt;element name="update-by-custodian" type="{urn:com.microsoft.wc.methods.AuthorizeRecord}UpdateByCustodian"/>
 *           &lt;element name="update-by-non-custodian" type="{urn:com.microsoft.wc.methods.AuthorizeRecord}UpdateByNonCustodian"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "userInitiatedCreationUsingEmail",
    "resendAuthorizationEmail",
    "appBehestCreation2",
    "updateByCustodian",
    "updateByNonCustodian"
})
public class AuthorizeRecordRequest {

    @XmlElement(name = "user-initiated-creation-using-email")
    protected UserInitiatedCreationUsingEmail userInitiatedCreationUsingEmail;
    @XmlElement(name = "resend-authorization-email")
    protected ResendAuthorizationEmail resendAuthorizationEmail;
    @XmlElement(name = "app-behest-creation2")
    protected AppBehestCreation2 appBehestCreation2;
    @XmlElement(name = "update-by-custodian")
    protected UpdateByCustodian updateByCustodian;
    @XmlElement(name = "update-by-non-custodian")
    protected UpdateByNonCustodian updateByNonCustodian;

    /**
     * Gets the value of the userInitiatedCreationUsingEmail property.
     * 
     * @return
     *     possible object is
     *     {@link UserInitiatedCreationUsingEmail }
     *     
     */
    public UserInitiatedCreationUsingEmail getUserInitiatedCreationUsingEmail() {
        return userInitiatedCreationUsingEmail;
    }

    /**
     * Sets the value of the userInitiatedCreationUsingEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserInitiatedCreationUsingEmail }
     *     
     */
    public void setUserInitiatedCreationUsingEmail(UserInitiatedCreationUsingEmail value) {
        this.userInitiatedCreationUsingEmail = value;
    }

    /**
     * Gets the value of the resendAuthorizationEmail property.
     * 
     * @return
     *     possible object is
     *     {@link ResendAuthorizationEmail }
     *     
     */
    public ResendAuthorizationEmail getResendAuthorizationEmail() {
        return resendAuthorizationEmail;
    }

    /**
     * Sets the value of the resendAuthorizationEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResendAuthorizationEmail }
     *     
     */
    public void setResendAuthorizationEmail(ResendAuthorizationEmail value) {
        this.resendAuthorizationEmail = value;
    }

    /**
     * Gets the value of the appBehestCreation2 property.
     * 
     * @return
     *     possible object is
     *     {@link AppBehestCreation2 }
     *     
     */
    public AppBehestCreation2 getAppBehestCreation2() {
        return appBehestCreation2;
    }

    /**
     * Sets the value of the appBehestCreation2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppBehestCreation2 }
     *     
     */
    public void setAppBehestCreation2(AppBehestCreation2 value) {
        this.appBehestCreation2 = value;
    }

    /**
     * Gets the value of the updateByCustodian property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateByCustodian }
     *     
     */
    public UpdateByCustodian getUpdateByCustodian() {
        return updateByCustodian;
    }

    /**
     * Sets the value of the updateByCustodian property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateByCustodian }
     *     
     */
    public void setUpdateByCustodian(UpdateByCustodian value) {
        this.updateByCustodian = value;
    }

    /**
     * Gets the value of the updateByNonCustodian property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateByNonCustodian }
     *     
     */
    public UpdateByNonCustodian getUpdateByNonCustodian() {
        return updateByNonCustodian;
    }

    /**
     * Sets the value of the updateByNonCustodian property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateByNonCustodian }
     *     
     */
    public void setUpdateByNonCustodian(UpdateByNonCustodian value) {
        this.updateByNonCustodian = value;
    }

}
