//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:25:08 AM PDT 
//


package com.microsoft.healthvault.thing;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.microsoft.healthvault.types.dates.DateTime;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:this="urn:com.microsoft.wc.thing.task"&gt;
 *                     A schedule for when the task is to be performed.
 *                 &lt;/summary&gt;
 * </pre>
 * 
 * 
 * <p>Java class for task-schedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="task-schedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="start-date-time" type="{urn:com.microsoft.wc.dates}date-time"/>
 *         &lt;element name="end-date-time" type="{urn:com.microsoft.wc.dates}date-time" minOccurs="0"/>
 *         &lt;element name="schedule-type" type="{urn:com.microsoft.wc.thing.task}task-schedule-type"/>
 *         &lt;element name="recurrence-type" type="{urn:com.microsoft.wc.thing.task}task-recurrence-type"/>
 *         &lt;element name="group-id" type="{urn:com.microsoft.wc.thing.types}stringnznw" minOccurs="0"/>
 *         &lt;element name="multiple" type="{urn:com.microsoft.wc.thing.types}positiveInt" minOccurs="0"/>
 *         &lt;element name="minutes-to-remind-before" type="{urn:com.microsoft.wc.thing.types}nonNegativeDouble" minOccurs="0"/>
 *         &lt;element name="adherence-window-in-minutes" type="{urn:com.microsoft.wc.thing.types}nonNegativeDouble" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "task-schedule", namespace = "urn:com.microsoft.wc.thing.task", propOrder = {
    "startDateTime",
    "endDateTime",
    "scheduleType",
    "recurrenceType",
    "groupId",
    "multiple",
    "minutesToRemindBefore",
    "adherenceWindowInMinutes"
})
public class TaskSchedule {

    @XmlElement(name = "start-date-time", required = true)
    protected DateTime startDateTime;
    @XmlElement(name = "end-date-time")
    protected DateTime endDateTime;
    @XmlElement(name = "schedule-type", required = true)
    @XmlSchemaType(name = "string")
    protected TaskScheduleType scheduleType;
    @XmlElement(name = "recurrence-type", required = true)
    @XmlSchemaType(name = "string")
    protected TaskRecurrenceType recurrenceType;
    @XmlElement(name = "group-id")
    protected String groupId;
    protected Integer multiple;
    @XmlElement(name = "minutes-to-remind-before")
    protected Double minutesToRemindBefore;
    @XmlElement(name = "adherence-window-in-minutes")
    protected Double adherenceWindowInMinutes;

    /**
     * Gets the value of the startDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getStartDateTime() {
        return startDateTime;
    }

    /**
     * Sets the value of the startDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setStartDateTime(DateTime value) {
        this.startDateTime = value;
    }

    /**
     * Gets the value of the endDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getEndDateTime() {
        return endDateTime;
    }

    /**
     * Sets the value of the endDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setEndDateTime(DateTime value) {
        this.endDateTime = value;
    }

    /**
     * Gets the value of the scheduleType property.
     * 
     * @return
     *     possible object is
     *     {@link TaskScheduleType }
     *     
     */
    public TaskScheduleType getScheduleType() {
        return scheduleType;
    }

    /**
     * Sets the value of the scheduleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskScheduleType }
     *     
     */
    public void setScheduleType(TaskScheduleType value) {
        this.scheduleType = value;
    }

    /**
     * Gets the value of the recurrenceType property.
     * 
     * @return
     *     possible object is
     *     {@link TaskRecurrenceType }
     *     
     */
    public TaskRecurrenceType getRecurrenceType() {
        return recurrenceType;
    }

    /**
     * Sets the value of the recurrenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskRecurrenceType }
     *     
     */
    public void setRecurrenceType(TaskRecurrenceType value) {
        this.recurrenceType = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the multiple property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMultiple() {
        return multiple;
    }

    /**
     * Sets the value of the multiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMultiple(Integer value) {
        this.multiple = value;
    }

    /**
     * Gets the value of the minutesToRemindBefore property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinutesToRemindBefore() {
        return minutesToRemindBefore;
    }

    /**
     * Sets the value of the minutesToRemindBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinutesToRemindBefore(Double value) {
        this.minutesToRemindBefore = value;
    }

    /**
     * Gets the value of the adherenceWindowInMinutes property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdherenceWindowInMinutes() {
        return adherenceWindowInMinutes;
    }

    /**
     * Sets the value of the adherenceWindowInMinutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdherenceWindowInMinutes(Double value) {
        this.adherenceWindowInMinutes = value;
    }

}
