//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.08.01 at 11:25:08 AM PDT
//


package com.microsoft.healthvault.methods.setapplicationsettings.request;


import com.microsoft.healthvault.methods.request.HVMethodRequest;
import com.microsoft.healthvault.methods.request.HVRequestInfo;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementMap;
import org.simpleframework.xml.Order;
import org.simpleframework.xml.Root;
import org.simpleframework.xml.Text;

import java.util.HashMap;

/**
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.SetApplicationSettings" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *                     The element of the request that contains the method
 *                     specific parameters.
 *                 &lt;/summary&gt;
 * </pre>
 *
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.SetApplicationSettings" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *                     All requests contain the info element to pass parameters
 *                     that are specific to each method. If the method does not
 *                     define an info element, the method does not take any
 *                     parameters.
 *                 &lt;/remarks&gt;
 * </pre>
 *
 *
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="app-settings" type="{urn:com.microsoft.wc.methods.SetApplicationSettings}AppSettings" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@Root(name = "info")
@HVMethodRequest(methodName="SetApplicationSettings", methodVersion="1")
@Order(elements = {
        "app-settings"
})
public class SetApplicationSettingsRequest implements HVRequestInfo {

    @Element(name="app-settings")
    protected AppSettings appSettings;

    /**
     * Gets the value of the appSettings property.
     *
     * @return
     *     possible object is
     *     {@link AppSettings }
     *
     */
    public AppSettings getAppSettings() {
        return appSettings;
    }

    /**
     * Sets the value of the appSettings property.
     *
     * @param value
     *     allowed object is
     *     {@link AppSettings }
     *
     */
    public void setAppSettings(AppSettings value) {
        this.appSettings = value;
    }

}
