//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:25:08 AM PDT 
//


package com.microsoft.healthvault.core.subscription;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.subscription" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *                     Defines the criteria when the event will fire.
 *                 &lt;/summary&gt;
 * </pre>
 * 
 * 
 * <p>Java class for RecordItemChangedEventFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecordItemChangedEventFilter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type-ids" type="{urn:com.microsoft.wc.subscription}TypeIds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordItemChangedEventFilter", namespace = "urn:com.microsoft.wc.subscription", propOrder = {
    "typeIds"
})
public class RecordItemChangedEventFilter {

    @XmlElement(name = "type-ids", required = true)
    protected TypeIds typeIds;

    /**
     * Gets the value of the typeIds property.
     * 
     * @return
     *     possible object is
     *     {@link TypeIds }
     *     
     */
    public TypeIds getTypeIds() {
        return typeIds;
    }

    /**
     * Sets the value of the typeIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeIds }
     *     
     */
    public void setTypeIds(TypeIds value) {
        this.typeIds = value;
    }

}
