//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:25:08 AM PDT 
//


package com.microsoft.healthvault.methods.GetApplicationDirectory.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.microsoft.healthvault.core.directory.DirectoryFilterSpec;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:directory="urn:com.microsoft.wc.directory" xmlns:this="urn:com.microsoft.wc.methods.GetApplicationDirectory" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *             The element of the request that contains the method
 *             specific parameters.
 *           &lt;/summary&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:directory="urn:com.microsoft.wc.directory" xmlns:this="urn:com.microsoft.wc.methods.GetApplicationDirectory" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *             All requests contain the info element to pass parameters
 *             that are specific to each method. If the method does not
 *             define an info element, the method does not take any
 *             parameters.
 *           &lt;/remarks&gt;
 * </pre>
 * 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="application-directory-filter" type="{urn:com.microsoft.wc.directory}DirectoryFilterSpec" minOccurs="0"/>
 *         &lt;element name="application-directory-id-cursor" type="{urn:com.microsoft.wc.types}stringnz" minOccurs="0"/>
 *         &lt;element name="include-item-details" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationDirectoryFilter",
    "applicationDirectoryIdCursor",
    "includeItemDetails"
})
public class GetApplicationDirectoryRequest {

    @XmlElement(name = "application-directory-filter")
    protected DirectoryFilterSpec applicationDirectoryFilter;
    @XmlElement(name = "application-directory-id-cursor")
    protected String applicationDirectoryIdCursor;
    @XmlElement(name = "include-item-details")
    protected Boolean includeItemDetails;

    /**
     * Gets the value of the applicationDirectoryFilter property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryFilterSpec }
     *     
     */
    public DirectoryFilterSpec getApplicationDirectoryFilter() {
        return applicationDirectoryFilter;
    }

    /**
     * Sets the value of the applicationDirectoryFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryFilterSpec }
     *     
     */
    public void setApplicationDirectoryFilter(DirectoryFilterSpec value) {
        this.applicationDirectoryFilter = value;
    }

    /**
     * Gets the value of the applicationDirectoryIdCursor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationDirectoryIdCursor() {
        return applicationDirectoryIdCursor;
    }

    /**
     * Sets the value of the applicationDirectoryIdCursor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationDirectoryIdCursor(String value) {
        this.applicationDirectoryIdCursor = value;
    }

    /**
     * Gets the value of the includeItemDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeItemDetails() {
        return includeItemDetails;
    }

    /**
     * Sets the value of the includeItemDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeItemDetails(Boolean value) {
        this.includeItemDetails = value;
    }

}
