//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.07 at 01:40:36 AM PST 
//


package com.microsoft.hsg.thing.oxm.jaxb.familyhistory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.microsoft.hsg.thing.oxm.jaxb.base.CodableValue;
import com.microsoft.hsg.thing.oxm.jaxb.base.Person;
import com.microsoft.hsg.thing.oxm.jaxb.dates.ApproxDate;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:d="urn:com.microsoft.wc.dates" xmlns:t="urn:com.microsoft.wc.thing.types" xmlns:this="urn:com.microsoft.wc.thing.family-history"&gt;
 *                     Information describing a relative.
 *                 &lt;/summary&gt;
 * </pre>
 * 
 * 
 * <p>Java class for FamilyHistoryRelative complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FamilyHistoryRelative">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="relative-name" type="{urn:com.microsoft.wc.thing.types}person" minOccurs="0"/>
 *         &lt;element name="relationship" type="{urn:com.microsoft.wc.thing.types}codable-value" minOccurs="0"/>
 *         &lt;element name="date-of-birth" type="{urn:com.microsoft.wc.dates}approx-date" minOccurs="0"/>
 *         &lt;element name="date-of-death" type="{urn:com.microsoft.wc.dates}approx-date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FamilyHistoryRelative", propOrder = {
    "relativeName",
    "relationship",
    "dateOfBirth",
    "dateOfDeath"
})
public class FamilyHistoryRelative {

    @XmlElement(name = "relative-name")
    protected Person relativeName;
    protected CodableValue relationship;
    @XmlElement(name = "date-of-birth")
    protected ApproxDate dateOfBirth;
    @XmlElement(name = "date-of-death")
    protected ApproxDate dateOfDeath;

    /**
     * Gets the value of the relativeName property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getRelativeName() {
        return relativeName;
    }

    /**
     * Sets the value of the relativeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setRelativeName(Person value) {
        this.relativeName = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link CodableValue }
     *     
     */
    public CodableValue getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodableValue }
     *     
     */
    public void setRelationship(CodableValue value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link ApproxDate }
     *     
     */
    public ApproxDate getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApproxDate }
     *     
     */
    public void setDateOfBirth(ApproxDate value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the dateOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link ApproxDate }
     *     
     */
    public ApproxDate getDateOfDeath() {
        return dateOfDeath;
    }

    /**
     * Sets the value of the dateOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApproxDate }
     *     
     */
    public void setDateOfDeath(ApproxDate value) {
        this.dateOfDeath = value;
    }

}
