//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:25:08 AM PDT 
//


package com.microsoft.healthvault.methods.SearchVocabulary.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.microsoft.healthvault.client.request.HVMethodRequest;
import com.microsoft.healthvault.client.request.HVRequestInfo;
import com.microsoft.healthvault.vocabulary.VocabularyKey;

import org.simpleframework.xml.Root;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.SearchVocabulary" xmlns:wc-types="urn:com.microsoft.wc.types" xmlns:wc-vocab="urn:com.microsoft.wc.vocab"&gt;
 *                         The element of the request that contains the method
 *                         specific parameters.
 *                     &lt;/summary&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.SearchVocabulary" xmlns:wc-types="urn:com.microsoft.wc.types" xmlns:wc-vocab="urn:com.microsoft.wc.vocab"/&gt;
 * </pre>
 * 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vocabulary-key" type="{urn:com.microsoft.wc.vocab}VocabularyKey" minOccurs="0"/>
 *         &lt;element name="text-search-parameters" type="{urn:com.microsoft.wc.methods.SearchVocabulary}VocabularySearchParams"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Root(name = "info")
@HVMethodRequest(methodName="SearchVocabulary", methodVersion="1")
@XmlType(name = "", propOrder = {
    "vocabularyKey",
    "textSearchParameters"
})
public class SearchVocabularyRequest implements HVRequestInfo {

    @XmlElement(name = "vocabulary-key")
    protected VocabularyKey vocabularyKey;
    @XmlElement(name = "text-search-parameters", required = true)
    protected VocabularySearchParams textSearchParameters;

    /**
     * Gets the value of the vocabularyKey property.
     * 
     * @return
     *     possible object is
     *     {@link VocabularyKey }
     *     
     */
    public VocabularyKey getVocabularyKey() {
        return vocabularyKey;
    }

    /**
     * Sets the value of the vocabularyKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocabularyKey }
     *     
     */
    public void setVocabularyKey(VocabularyKey value) {
        this.vocabularyKey = value;
    }

    /**
     * Gets the value of the textSearchParameters property.
     * 
     * @return
     *     possible object is
     *     {@link VocabularySearchParams }
     *     
     */
    public VocabularySearchParams getTextSearchParameters() {
        return textSearchParameters;
    }

    /**
     * Sets the value of the textSearchParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocabularySearchParams }
     *     
     */
    public void setTextSearchParameters(VocabularySearchParams value) {
        this.textSearchParameters = value;
    }

}
