//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:25:08 AM PDT 
//


package com.microsoft.healthvault.methods.UpdateCredential.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.microsoft.healthvault.core.authentication.AssociatedCredInfo;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wc-auth="urn:com.microsoft.wc.auth" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *                         The associated credential info identifying which credential
 *                         to update along with the metadata and name to update.
 *                     &lt;/summary&gt;
 * </pre>
 * 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="credential-info" type="{urn:com.microsoft.wc.auth}AssociatedCredInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "credentialInfo"
})
public class UpdateCredentialRequest {

    @XmlElement(name = "credential-info", required = true)
    protected AssociatedCredInfo credentialInfo;

    /**
     * Gets the value of the credentialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedCredInfo }
     *     
     */
    public AssociatedCredInfo getCredentialInfo() {
        return credentialInfo;
    }

    /**
     * Sets the value of the credentialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedCredInfo }
     *     
     */
    public void setCredentialInfo(AssociatedCredInfo value) {
        this.credentialInfo = value;
    }

}
