/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.healthvault.restapi.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A goal recommendation being created for a user.
 */
public class GoalRecommendation {
    /**
     * The expiration date of the recommendation in Universal Time Zone(UTC).
     */
    @JsonProperty(value = "expirationDate")
    private DateTime expirationDate;

    /**
     * The associated goal data.
     */
    @JsonProperty(value = "associatedGoal")
    private Goal associatedGoal;

    /**
     * Get the expirationDate value.
     *
     * @return the expirationDate value
     */
    public DateTime expirationDate() {
        return this.expirationDate;
    }

    /**
     * Set the expirationDate value.
     *
     * @param expirationDate the expirationDate value to set
     * @return the GoalRecommendation object itself.
     */
    public GoalRecommendation withExpirationDate(DateTime expirationDate) {
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * Get the associatedGoal value.
     *
     * @return the associatedGoal value
     */
    public Goal associatedGoal() {
        return this.associatedGoal;
    }

    /**
     * Set the associatedGoal value.
     *
     * @param associatedGoal the associatedGoal value to set
     * @return the GoalRecommendation object itself.
     */
    public GoalRecommendation withAssociatedGoal(Goal associatedGoal) {
        this.associatedGoal = associatedGoal;
        return this;
    }

}
