/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.healthvault.restapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * class for Tracking Validation.
 */
public class TrackingValidation {
    /**
     * Gets or sets the action plan task.
     */
    @JsonProperty(value = "actionPlanTask")
    private ActionPlanTask actionPlanTask;

    /**
     * Gets or sets the XML thing document.
     */
    @JsonProperty(value = "xmlThingDocument")
    private String xmlThingDocument;

    /**
     * Get the actionPlanTask value.
     *
     * @return the actionPlanTask value
     */
    public ActionPlanTask actionPlanTask() {
        return this.actionPlanTask;
    }

    /**
     * Set the actionPlanTask value.
     *
     * @param actionPlanTask the actionPlanTask value to set
     * @return the TrackingValidation object itself.
     */
    public TrackingValidation withActionPlanTask(ActionPlanTask actionPlanTask) {
        this.actionPlanTask = actionPlanTask;
        return this;
    }

    /**
     * Get the xmlThingDocument value.
     *
     * @return the xmlThingDocument value
     */
    public String xmlThingDocument() {
        return this.xmlThingDocument;
    }

    /**
     * Set the xmlThingDocument value.
     *
     * @param xmlThingDocument the xmlThingDocument value to set
     * @return the TrackingValidation object itself.
     */
    public TrackingValidation withXmlThingDocument(String xmlThingDocument) {
        this.xmlThingDocument = xmlThingDocument;
        return this;
    }

}
