//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 08:13:00 PM PST 
//


package com.microsoft.hsg.methods.jaxb.getauthorizedpeople.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.microsoft.hsg.methods.jaxb.JaxbRequest;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.GetAuthorizedPeople" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *             The element of the request that contains the method
 *             specific parameters.
 *           &lt;/summary&gt;
 * </pre>
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;remarks xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.methods.GetAuthorizedPeople" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *             All requests contain the info element to pass parameters
 *             that are specific to each method. If the method does not
 *             define an info element, the method does not take any
 *             parameters.
 *           &lt;/remarks&gt;
 * </pre>
 * 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameters" type="{urn:com.microsoft.wc.methods.GetAuthorizedPeople}GetAuthorizedPeopleParameters"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@JaxbRequest(
		methodName = "GetAuthorizedPeople",
		methodVersion = "1",
		responseNS = "urn:com.microsoft.wc.methods.response.GetAuthorizedPeople")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameters"
})
@XmlRootElement(name = "info")
public class GetAuthorizedPeopleRequest {

    @XmlElement(required = true)
    protected GetAuthorizedPeopleParameters parameters;

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link GetAuthorizedPeopleParameters }
     *     
     */
    public GetAuthorizedPeopleParameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetAuthorizedPeopleParameters }
     *     
     */
    public void setParameters(GetAuthorizedPeopleParameters value) {
        this.parameters = value;
    }

}
