//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.03 at 08:22:44 PM PST 
//


package com.microsoft.hsg.methods.jaxb.auth;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:this="urn:com.microsoft.wc.auth" xmlns:wc-thing="urn:com.microsoft.wc.thing" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *                     Info used to describe the credential to associated with
 *                     the account.
 *                 &lt;/summary&gt;
 * </pre>
 * 
 * 
 * <p>Java class for AssociatedCredInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssociatedCredInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="credential" type="{urn:com.microsoft.wc.auth}SimpleCardSpaceCredential"/>
 *           &lt;element name="simple-userpass" type="{urn:com.microsoft.wc.auth}UserPassCred"/>
 *           &lt;element name="simple-passport" type="{urn:com.microsoft.wc.auth}SimplePassportCredential"/>
 *           &lt;element name="simple-openid" type="{urn:com.microsoft.wc.auth}SimpleOpenIdCredential"/>
 *         &lt;/choice>
 *         &lt;element name="credential-metadata" type="{urn:com.microsoft.wc.types}stringnz" minOccurs="0"/>
 *         &lt;element name="credential-name" type="{urn:com.microsoft.wc.types}string64" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssociatedCredInfo", propOrder = {
    "credential",
    "simpleUserpass",
    "simplePassport",
    "simpleOpenid",
    "credentialMetadata",
    "credentialName"
})
public class AssociatedCredInfo {

    protected SimpleCardSpaceCredential credential;
    @XmlElement(name = "simple-userpass")
    protected UserPassCred simpleUserpass;
    @XmlElement(name = "simple-passport")
    protected SimplePassportCredential simplePassport;
    @XmlElement(name = "simple-openid")
    protected SimpleOpenIdCredential simpleOpenid;
    @XmlElement(name = "credential-metadata")
    protected String credentialMetadata;
    @XmlElement(name = "credential-name")
    protected String credentialName;

    /**
     * Gets the value of the credential property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleCardSpaceCredential }
     *     
     */
    public SimpleCardSpaceCredential getCredential() {
        return credential;
    }

    /**
     * Sets the value of the credential property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleCardSpaceCredential }
     *     
     */
    public void setCredential(SimpleCardSpaceCredential value) {
        this.credential = value;
    }

    /**
     * Gets the value of the simpleUserpass property.
     * 
     * @return
     *     possible object is
     *     {@link UserPassCred }
     *     
     */
    public UserPassCred getSimpleUserpass() {
        return simpleUserpass;
    }

    /**
     * Sets the value of the simpleUserpass property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserPassCred }
     *     
     */
    public void setSimpleUserpass(UserPassCred value) {
        this.simpleUserpass = value;
    }

    /**
     * Gets the value of the simplePassport property.
     * 
     * @return
     *     possible object is
     *     {@link SimplePassportCredential }
     *     
     */
    public SimplePassportCredential getSimplePassport() {
        return simplePassport;
    }

    /**
     * Sets the value of the simplePassport property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimplePassportCredential }
     *     
     */
    public void setSimplePassport(SimplePassportCredential value) {
        this.simplePassport = value;
    }

    /**
     * Gets the value of the simpleOpenid property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleOpenIdCredential }
     *     
     */
    public SimpleOpenIdCredential getSimpleOpenid() {
        return simpleOpenid;
    }

    /**
     * Sets the value of the simpleOpenid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleOpenIdCredential }
     *     
     */
    public void setSimpleOpenid(SimpleOpenIdCredential value) {
        this.simpleOpenid = value;
    }

    /**
     * Gets the value of the credentialMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredentialMetadata() {
        return credentialMetadata;
    }

    /**
     * Sets the value of the credentialMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredentialMetadata(String value) {
        this.credentialMetadata = value;
    }

    /**
     * Gets the value of the credentialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredentialName() {
        return credentialName;
    }

    /**
     * Sets the value of the credentialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredentialName(String value) {
        this.credentialName = value;
    }

}
