//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 10:00:29 PM PDT 
//


package com.microsoft.hsg.methods.jaxb.getdevicedirectory.response;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;summary xmlns="http://www.w3.org/2001/XMLSchema" xmlns:directory="urn:com.microsoft.wc.directory" xmlns:this="urn:com.microsoft.wc.methods.response.GetDeviceDirectory" xmlns:wc-types="urn:com.microsoft.wc.types"&gt;
 *             The device directory entries returned for HealthVault.
 *           &lt;/summary&gt;
 * </pre>
 * 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="device-directory" type="{urn:com.microsoft.wc.methods.response.GetDeviceDirectory}DeviceDirectory" minOccurs="0"/>
 *         &lt;element name="total-item-count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="device-directory-id-cursor" type="{urn:com.microsoft.wc.types}stringnz" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deviceDirectory",
    "totalItemCount",
    "deviceDirectoryIdCursor"
})
@XmlRootElement(name = "info")
public class GetDeviceDirectoryResponse {

    @XmlElement(name = "device-directory")
    protected DeviceDirectory deviceDirectory;
    @XmlElement(name = "total-item-count")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger totalItemCount;
    @XmlElement(name = "device-directory-id-cursor")
    protected String deviceDirectoryIdCursor;

    /**
     * Gets the value of the deviceDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceDirectory }
     *     
     */
    public DeviceDirectory getDeviceDirectory() {
        return deviceDirectory;
    }

    /**
     * Sets the value of the deviceDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceDirectory }
     *     
     */
    public void setDeviceDirectory(DeviceDirectory value) {
        this.deviceDirectory = value;
    }

    /**
     * Gets the value of the totalItemCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalItemCount() {
        return totalItemCount;
    }

    /**
     * Sets the value of the totalItemCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalItemCount(BigInteger value) {
        this.totalItemCount = value;
    }

    /**
     * Gets the value of the deviceDirectoryIdCursor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceDirectoryIdCursor() {
        return deviceDirectoryIdCursor;
    }

    /**
     * Sets the value of the deviceDirectoryIdCursor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceDirectoryIdCursor(String value) {
        this.deviceDirectoryIdCursor = value;
    }

}
