/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.healthvault.restapi.models;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * The ErrorInformation model.
 */
public class ErrorInformation {
    /**
     * The code property.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * The message property.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The target property.
     */
    @JsonProperty(value = "target")
    private String target;

    /**
     * The details property.
     */
    @JsonProperty(value = "details")
    private List<ErrorInformation> details;

    /**
     * The innererror property.
     */
    @JsonProperty(value = "innererror")
    private ErrorInformation innererror;

    /**
     * The exception property.
     */
    @JsonProperty(value = "exception")
    private Object exception;

    /**
     * Get the code value.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set the code value.
     *
     * @param code the code value to set
     * @return the ErrorInformation object itself.
     */
    public ErrorInformation withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the ErrorInformation object itself.
     */
    public ErrorInformation withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the target value.
     *
     * @return the target value
     */
    public String target() {
        return this.target;
    }

    /**
     * Set the target value.
     *
     * @param target the target value to set
     * @return the ErrorInformation object itself.
     */
    public ErrorInformation withTarget(String target) {
        this.target = target;
        return this;
    }

    /**
     * Get the details value.
     *
     * @return the details value
     */
    public List<ErrorInformation> details() {
        return this.details;
    }

    /**
     * Set the details value.
     *
     * @param details the details value to set
     * @return the ErrorInformation object itself.
     */
    public ErrorInformation withDetails(List<ErrorInformation> details) {
        this.details = details;
        return this;
    }

    /**
     * Get the innererror value.
     *
     * @return the innererror value
     */
    public ErrorInformation innererror() {
        return this.innererror;
    }

    /**
     * Set the innererror value.
     *
     * @param innererror the innererror value to set
     * @return the ErrorInformation object itself.
     */
    public ErrorInformation withInnererror(ErrorInformation innererror) {
        this.innererror = innererror;
        return this;
    }

    /**
     * Get the exception value.
     *
     * @return the exception value
     */
    public Object exception() {
        return this.exception;
    }

    /**
     * Set the exception value.
     *
     * @param exception the exception value to set
     * @return the ErrorInformation object itself.
     */
    public ErrorInformation withException(Object exception) {
        this.exception = exception;
        return this;
    }

}
