/**
 * Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.healthvault.restapi.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The goal recommendations response.
 */
public class GoalRecommendationsResponse {
    /**
     * The collection of goal recommendations.
     */
    @JsonProperty(value = "goalRecommendations")
    private List<GoalRecommendationInstance> goalRecommendations;

    /**
     * The URI for the next page of data.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the goalRecommendations value.
     *
     * @return the goalRecommendations value
     */
    public List<GoalRecommendationInstance> goalRecommendations() {
        return this.goalRecommendations;
    }

    /**
     * Set the goalRecommendations value.
     *
     * @param goalRecommendations the goalRecommendations value to set
     * @return the GoalRecommendationsResponse object itself.
     */
    public GoalRecommendationsResponse withGoalRecommendations(List<GoalRecommendationInstance> goalRecommendations) {
        this.goalRecommendations = goalRecommendations;
        return this;
    }

    /**
     * Get the nextLink value.
     *
     * @return the nextLink value
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink value.
     *
     * @param nextLink the nextLink value to set
     * @return the GoalRecommendationsResponse object itself.
     */
    public GoalRecommendationsResponse withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }

}
