//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:25:08 AM PDT 
//


package com.microsoft.healthvault.methods.QueryPersons2.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.microsoft.healthvault.methods.QueryPersons2.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.healthvault.methods.QueryPersons2.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryPersons2Request }
     * 
     */
    public QueryPersons2Request createQueryPersons2Request() {
        return new QueryPersons2Request();
    }

    /**
     * Create an instance of {@link QueryPersonsFilterSpec }
     * 
     */
    public QueryPersonsFilterSpec createQueryPersonsFilterSpec() {
        return new QueryPersonsFilterSpec();
    }

    /**
     * Create an instance of {@link QueryPersonsViewSpec }
     * 
     */
    public QueryPersonsViewSpec createQueryPersonsViewSpec() {
        return new QueryPersonsViewSpec();
    }

    /**
     * Create an instance of {@link QueryPersonsStateSpec }
     * 
     */
    public QueryPersonsStateSpec createQueryPersonsStateSpec() {
        return new QueryPersonsStateSpec();
    }

}
